apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rabbitmq-endpoint-reader
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: rabbitmq-server
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-rabbitmq-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-rabbitmq-endpoint-reader