kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-rabbitmq-svc
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: rabbitmq-server
spec:
  ports:
  - name: client-access-2
    port: 5672
  - name: client-access-1
    port: 5671
  - name: clitool
    port: 25672
  - name: epmd
    port: 4369
  - name: http
    port: 15672
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: rabbitmq-server
  type: LoadBalancer
